### ISSUE TITLE
Suggestion: adding xen support (booting out of sbxg :-)

### ISSUE THREAD

**Issue by Jerome-Maurin** [sbxg/sbxg#17]
I have tested with succes on the Cubietruck Xen for arm using Xen & the Kernel provided by Debian.

Sbxg could provide the option to build a Image containing both the Dom0 and a DomU.

Please not that with a 100M space for the initrd, even the 2536 kernel modules from jean-marc should fit in ram !!!

Here is the boot.cmd (source of the boot.scr) needed:
```
# SUNXI Xen Boot Script

# in order to 'compile', please enter :
# mkimage -C none -A arm -T script -d /boot/boot.cmd /boot/boot.scr

# Requirements for this script to work
# (you can use symbolic links to point to the correct file) :
# - recent enough u-boot to support the bootz command
# - Xen Kernel using the zImage (default in Debian package) format at /boot/xen
# - Kernel using the zImage format at /boot/zImage
# - Initrd using the initramfs format at /boot/initrd
#   (example for debian the update-initramfs command can be used to create it)
# - DTB using the device-tree binary format provided by the kernel at /boot/dtb
#   (for example, if using a Debian Kernel package, look for the dtb
#   corresponding to your board in /usr/lib/KERNEL_NAME/)

# Top of RAM:         0xc0000000
# Xen relocate addr   0xbfe00000 # 2M
setenv kernel_addr_r  0xbf600000 # 8M
setenv ramdisk_addr_r 0xbc200000 # 100M
setenv fdt_addr       0xbc000000 # 2M
setenv xen_addr_r     0xbbe00000 # 2M

setenv fdt_high       0xffffffff # Load fdt in place instead of relocating

# Load  xen/xen  to ${xen_addr_r}. e.g.  tftp,  fatload or ext2load to
# ${xen_addr_r}.   see the following  sections  for details of booting
# from various devices.

ext2load mmc 0 ${xen_addr_r} boot/xen

setenv bootargs "console=dtuart dtuart=/soc@01c00000/serial@01c28000 dom0_mem=512M flask=disabled guest_loglvl=all loglvl=all iommu=debug"

# Load  appropriate .dtb file to   ${fdt_addr}  e.g. tftp, fatload  or
# ext2load to ${fdt_addr}.  see  the following sections for details of
# booting from various devices.

ext2load mmc 0 ${fdt_addr} boot/dtb

fdt addr ${fdt_addr} 0x40000

fdt resize

fdt chosen

fdt set /chosen \#address-cells <1>
fdt set /chosen \#size-cells <1>

# Load Linux  arch/arm/boot/zImage  to  ${kernel_addr_r}.  e.g.  tftp,
# fatload or ext2load to ${kernel_addr_r}.  see the following sections
# for details of booting from various devices.

ext2load mmc 0 ${kernel_addr_r} boot/zImage

fdt mknod /chosen module@0
fdt set /chosen/module@0 compatible "xen,linux-zimage" "xen,multiboot-module"
fdt set /chosen/module@0 reg <${kernel_addr_r} 0x${filesize} >
fdt set /chosen/module@0 bootargs "earlyprintk console=hvc0 disp.screen0_output_type=3 hdmi.audio=EDID:0 disp.screen0_output_mode=EDID:1280x1024p60 root=/dev/mmcblk0p1 rootwait panic=10 clk_ignore_unused ${extra}"

ext2load mmc 0 ${ramdisk_addr_r} boot/initrd

fdt mknod /chosen module@1
fdt set /chosen/module@1 compatible "xen,linux-initrd" "xen,multiboot-module"
fdt set /chosen/module@1 reg <${ramdisk_addr_r} 0x${filesize} >

# Reserve for passthrough the hdmi frambuffer

#fdt set /chosen/framebuffer@0 xen,passthrough

bootz ${xen_addr_r} - ${fdt_addr}
```

And a basic configuration file for a DomU
```
name = "vm-debian"

memory = 256

vcpus = 2

vif = [ 'AA:BB:CC:DD:EE:FF,bridge=xenbr0' ]

kernel = "zImage"

ramdisk = "initrd"

# Linux cmdline
extra = ""

disk = [ "disk.img,,," ]
```

To start a domU use the "xl create CONFIG_FILE" to start a domU.

In debian put this file in /etc/xen/auto to have your domU started by init.

**Comment by jeanguyomarch** [comment]
Hi Jérôme,

> I have tested with succes on the Cubietruck Xen for arm using Xen & the Kernel provided by Debian.
Nice ! :)

> Sbxg could provide the option to build a Image containing both the Dom0 and a DomU.

It would be great to have Xen support in SBXG.
I just want Xen to be compiled from the sources. I haven't played with Xen myself, so I've never compiled/configured it, but a quick look at its sources would tend to suggest it is not that difficult, and I assume its integration to SBXG would not be a problem.

So okay, we could make SBXG build a U-boot + Xen kernel. We could use our linux subsystem + rootfs to create the dom0. I'd prefer the dom0 kernel to be compiled by us, as it is part of the trusted base of code. We can then install specific packages in the rootfs so we can have xen tools to manage domUs. 

But I think we should stop there. We can still use SBXG to generate a bundle kernel + initramfs + rootfs that could be used by as a domU, But that's another job for another tool. We can produce a fully operational (yet minimal) image ready to be flashed, but we should not attempt to do more.
So, to me, it is up to another tool (maybe just a script) to:
- use SBXG to generate whatever we need (Xen/rootfs/...);
- orchestrate successive runs of SBXG;
- push configuration files wherever we need.

Does this seem fair to you?

If you have started to do something in SBXG, I'll be more than happy to review a PR. Since adding support for other OSes really interests me, I could have a look at Xen and try to integrate it to SBXG myself. This would open the door to experimental things like [Xvisor](http://xhypervisor.org/index.php?page=home).

**Comment by Jerome-Maurin** [comment]
```
/dts-v1/;

/ {

    /* #*cells are here to keep DTC happy */
    #address-cells = <1>;
    #size-cells = <1>;


    passthrough {
        compatible = "simple-bus";
        ranges;
        #address-cells = <1>;
        #size-cells = <1>;
        framebuffer@bfc18000 {
                compatible = "allwinner,simple-framebuffer", "simple-framebuffer";
                clocks = <0x2 0x24 0x2 0x2b 0x2 0x2c 0x3 0x4 0x5 0x1a>;
                width = <0x500>;
                stride = <0x1400>;
                allwinner,pipeline = "de_be0-lcd0-hdmi";
                status = "okay";
                reg = <0xcfc18000 0x3e8000>;
                format = "x8r8g8b8";
                height = <0x320>;
        };
    };
};
```

**Comment by jeanguyomarch** [comment]
This is now supported in SBXG v2 :)
